[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = true
minify = "always"

[watch]
watch = ["src", "styles.css", "index.html", "assets"]
ignore = ["dist"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

