//! Progressive enhancement for the static article pages (generated by
//! `tools/blog`). They reuse this same wasm bundle purely for two runtime touches
//! that can't be baked at build time: a copy button on each code block and a
//! reading-progress bar. Everything degrades to the plain static HTML if the
//! bundle never loads.

use wasm_bindgen::closure::Closure;
use wasm_bindgen::JsCast;
use web_sys::{Document, Element, HtmlElement, Window};

/// True when the current page is under `/articles/` — the signal `main()` uses to
/// enhance instead of mounting the portfolio app.
pub fn is_article_page() -> bool {
    web_sys::window()
        .and_then(|w| w.location().pathname().ok())
        .is_some_and(|p| p.starts_with("/articles/"))
}

pub fn enhance() {
    let Some(win) = web_sys::window() else { return };
    let Some(doc) = win.document() else { return };
    add_copy_buttons(&doc);
    add_progress_bar(&win, &doc);
}

/// Drop a "Copy" button into each code block's language header.
fn add_copy_buttons(doc: &Document) {
    let Ok(figures) = doc.query_selector_all("figure.codeblock") else { return };
    for i in 0..figures.length() {
        let Some(node) = figures.item(i) else { continue };
        let figure: Element = node.unchecked_into();
        let (Ok(Some(caption)), Ok(Some(code))) =
            (figure.query_selector("figcaption"), figure.query_selector("pre code"))
        else {
            continue;
        };
        let text = code.text_content().unwrap_or_default();

        let Ok(button) = doc.create_element("button") else { continue };
        let _ = button.set_attribute("type", "button");
        let _ = button.set_attribute("class", "copy");
        button.set_text_content(Some("Copy"));

        let label: HtmlElement = button.clone().unchecked_into();
        let handler = Closure::<dyn FnMut()>::new(move || {
            if let Some(win) = web_sys::window() {
                let _ = win.navigator().clipboard().write_text(&text); // fire-and-forget
            }
            label.set_text_content(Some("Copied ✓"));
            let reset = label.clone();
            let revert = Closure::once_into_js(move || reset.set_text_content(Some("Copy")));
            if let Some(win) = web_sys::window() {
                let _ = win.set_timeout_with_callback_and_timeout_and_arguments_0(
                    revert.unchecked_ref(),
                    1400,
                );
            }
        });
        let _ = button.add_event_listener_with_callback("click", handler.as_ref().unchecked_ref());
        handler.forget(); // lives for the page's lifetime
        let _ = caption.append_child(&button);
    }
}

/// A thin fixed bar at the top of the viewport that fills as the article scrolls.
/// Skipped on the index / tag list pages, which carry no `<article>`.
fn add_progress_bar(win: &Window, doc: &Document) {
    if !matches!(doc.query_selector("article"), Ok(Some(_))) {
        return;
    }
    let Ok(bar) = doc.create_element("div") else { return };
    let _ = bar.set_attribute("class", "reading-progress");
    if let Some(body) = doc.body() {
        let _ = body.append_child(&bar);
    }
    let bar: HtmlElement = bar.unchecked_into();

    let win_ref = win.clone();
    let doc_ref = doc.clone();
    let update = Closure::<dyn FnMut()>::new(move || {
        let scrolled = win_ref.scroll_y().unwrap_or(0.0);
        let viewport = win_ref.inner_height().ok().and_then(|v| v.as_f64()).unwrap_or(0.0);
        let full = doc_ref.document_element().map_or(0.0, |el| el.scroll_height() as f64);
        let pct = (scrolled / (full - viewport).max(1.0) * 100.0).clamp(0.0, 100.0);
        let _ = bar.style().set_property("width", &format!("{pct}%"));
    });
    let _ = win.add_event_listener_with_callback("scroll", update.as_ref().unchecked_ref());
    update.forget();
}
